/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Archer = ({ containerRef, bowRef, arrow1Ref, ...props }) => {
  const { nodes, materials } = useGLTF("/bow_arrow.glb");
  return (
    <group ref={containerRef} dispose={null} position={[0.19, 0, 0]}>
      <group ref={arrow1Ref}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.arrow_arrow_mt_0.geometry}
          material={materials.arrow_mt}
          position={[-0.001, 0, 0.087]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.arrow_wing_mt_0.geometry}
          material={materials.wing_mt}
          position={[0.004, 0, -0.378]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group ref={bowRef} position={[-0.19, 0.603, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bow_bow_metal_mt_0.geometry}
          material={materials.bow_metal_mt}
          position={[0, 0, -0.034]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bow_bow_wood_mt_0.geometry}
          material={materials.bow_wood_mt}
          position={[0, 0, 0.034]}
          rotation={[0, -1.571, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/bow_arrow.glb");
