/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Target = ({ targetRef }) => {
  const { nodes, materials } = useGLTF("/target.glb");
  return (
    <group ref={targetRef} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.target.geometry}
        material={materials["target.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.frame.geometry}
        material={materials.wood}
      />
    </group>
  );
};

useGLTF.preload("/target.glb");
